<?php


$text = "BLAS LLANO
EMILIA ALFARO
MIRTA GUSINKY
RAMÓN GÓMEZ VERLANGIERI 
JULIO CÉSAR VELÁZQUEZ
OSCAR GONZÁLEZ DAHER 
GUSTAVO ALFONSO GONZÁLEZ 
ZULMA GÓMEZ
ENRIQUE BACCHETTA
ENZO CARDOZO
SILVIO OVELAR
JORGE OVIEDO MATTO 
JULIO QUIÑÓNEZ
JULIO FRANCO GÓMEZ 
LUIS WAGNER
BLANCA FONSECA
ÓSCAR SALOMÓN
JUAN DARÍO MONGES
VÍCTOR BOGADO
NELSON AGUINAGALDE
CARLOS NÚÑEZ AGÜERO 
JOSÉ BÓBEDA";

echo "php cli.php db:index\n";
foreach (explode("\n", $text) as $nombre) {
    $nombre = trim($nombre);
    echo "php cli.php corrupto:agregar  \"$nombre\"\n";
}
